# 1

In [39]:
#import numpy dan tensorflow
import numpy as np

In [40]:
a = np.array([[23,50],[7,12]])
b = np.array([[57,67],[99,43]])
c = np.array([[75,21],[57,12]])
d = np.array([[87,26],[18,84]])

In [41]:
tensor = np.array([a,b,c,d])
tensor

array([[[23, 50],
        [ 7, 12]],

       [[57, 67],
        [99, 43]],

       [[75, 21],
        [57, 12]],

       [[87, 26],
        [18, 84]]])

# 2

In [42]:
#Matrix A dan B
A = np.array([[23,50,19],[7,12,109],[57,67,98]])
B = np.array([[17],[22],[19]])

In [43]:
#A x B
A * B

array([[ 391,  850,  323],
       [ 154,  264, 2398],
       [1083, 1273, 1862]])

# 3

In [44]:
#Transpose matrix A
A.T

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

In [45]:
#determinan matrix A
np.linalg.det(A)

131344.0000000002

In [46]:
#inverse matrix A
np.linalg.inv(A)

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])