In [11]:
#import numpy
import numpy as np

In [23]:
#buat vektor
list1 = np.array([[17],
                [22],
                [19]])

In [28]:
#buat vektor A
vectorA = np.array([[17],
                    [22],
                    [19]])

#buat vektor B 
vectorB = np.array([[10],
                    [20],
                    [11]])

#buat vektor C
vectorC = np.array([[5],
                    [12],
                    [9]])

In [29]:
# A+B
vectorA + vectorB

array([[27],
       [42],
       [30]])

In [30]:
# B-C
vectorB - vectorC

array([[5],
       [8],
       [2]])

In [48]:
#A dot C
np.dot(vectorA, (np.transpose(vectorC)))

array([[ 85, 204, 153],
       [110, 264, 198],
       [ 95, 228, 171]])

In [33]:
#A x B
vectorA * vectorB

array([[170],
       [440],
       [209]])

In [46]:
#norm A

In [50]:
#sudut antara vektor A dan B
sudut = (np.dot(vectorA, (np.transpose(vectorB)))) / (np.linalg.norm(vectorA) * np.linalg.norm(vectorB))
sudut

array([[0.20258001, 0.40516003, 0.22283801],
       [0.26216237, 0.52432474, 0.28837861],
       [0.22641296, 0.45282591, 0.24905425]])

In [55]:
#buat vektor u
vectorU = np.array([[2],
                    [5]])

#buat vektor V
vectorV = np.array([[3],
                    [1]])

#import matplotlib
import matplotlib.pyplot as plt
